
all:
	cd k2tree && make all
	cd dk2tree && make all
	cd k2trie && make all
	cd sdk2tree && make all
	cd k2sdsl && make all

debug:
	cd k2tree && make debug
	cd dk2tree && make debug
	cd k2trie && make debug
	cd sdk2tree && make debug
	cd k2sdsl && make debug

clean:
	cd k2tree && make clean
	cd dk2tree && make clean
	cd k2trie && make clean
	cd sdk2tree && make clean
	cd k2sdsl && make clean